//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice4EntitiesWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public int ID_Book { get; set; }
        public string Title { get; set; }
        public Nullable<int> Genre_ID { get; set; }
        public Nullable<int> Author_ID { get; set; }
    
        public virtual Authors Authors { private get; set; }
        public virtual Genres Genres { private get; set; }
    }
}
